var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>(true)).Single(a=>a.name=="MANUKA_lilToon");var avatar=UnityEngine.Object.Instantiate(original.gameObject);avatar.name="Issue121 throat authoring probe";
try{
var descriptor=avatar.GetComponent<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>();var settings=LumaKroma.Sps2SetupAssistant.Editor.Model.FullSetupCatalog.CreateDefault();LumaKroma.Sps2SetupAssistant.Editor.Generation.Sps2SetupContext root;string error;var result=new System.Collections.Generic.List<string>();
if(!LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,true,out root,out error))return error;
var mouth=root.sockets.Single(s=>s.id=="mouth");var anus=root.sockets.Single(s=>s.id=="anus");var neck=avatar.GetComponent<UnityEngine.Animator>().GetBoneTransform(UnityEngine.HumanBodyBones.Neck);
result.Add("throatDistance="+UnityEngine.Vector3.Distance(mouth.pathStops[0].position,neck.position)+";mouthExitError="+UnityEngine.Vector3.Distance(mouth.pathStops[2].position,anus.pose.position)+";anusExitError="+UnityEngine.Vector3.Distance(anus.pathStops[2].position,mouth.pose.position));
var point=mouth.pathStops[0];point.localPosition+=new UnityEngine.Vector3(0,0,.002f);var adjusted=point.localPosition;
LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,false,out root,out error);result.Add("manualPathPreserved="+(root.sockets.Single(s=>s.id=="mouth").pathStops[0]==point&&point.localPosition==adjusted));
settings.penetration=false;LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,false,out root,out error);result.Add("offPathCounts="+string.Join(",",root.sockets.Where(s=>s.id=="mouth"||s.id=="anus").Select(s=>new UnityEditor.SerializedObject(s.socket).FindProperty("guidedPathStops").arraySize)));
settings.penetration=true;LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,false,out root,out error);result.Add("onCollapsed="+root.sockets.Where(s=>s.id=="mouth"||s.id=="anus").All(s=>Enumerable.Range(0,3).All(i=>new UnityEditor.SerializedObject(s.socket).FindProperty("guidedPathStops").GetArrayElementAtIndex(i).FindPropertyRelative("shrink").boolValue)));
UnityEditor.Selection.activeGameObject=original.gameObject;UnityEditor.Undo.FlushUndoRecordObjects();UnityEditor.Undo.PerformUndo();root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(descriptor);result.Add("undoOff="+!root.settings.penetration);UnityEditor.Undo.PerformRedo();root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(descriptor);result.Add("redoOn="+root.settings.penetration);
LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.ShowLongTestPlug(descriptor,out error);root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(descriptor);var capsule=root.longTestPlug.GetComponentInChildren<UnityEngine.MeshFilter>();result.Add("longPlugWidth="+capsule.sharedMesh.bounds.size.x*capsule.transform.localScale.x+";length="+capsule.sharedMesh.bounds.size.z*capsule.transform.localScale.z);
return result;
}finally{UnityEditor.Selection.activeGameObject=original.gameObject;UnityEngine.Object.DestroyImmediate(avatar);}
