using System.Collections.Generic;
using UnityEditor;

namespace LumaKroma.Sps2SetupAssistant.Editor.Localization
{
    public static class Sps2Localization
    {
        private const string PreferenceKey = "LumaKroma.Sps2SetupAssistant.UiLanguage";
        public static readonly string[] LanguageNames = { "日本語", "English", "한국어", "简体中文", "繁體中文" };
        public static DisplayLanguage UiLanguage
        {
            get => Normalize((DisplayLanguage)EditorPrefs.GetInt(PreferenceKey, 0));
            set => EditorPrefs.SetInt(PreferenceKey, (int)Normalize(value));
        }
        public static DisplayLanguage Normalize(DisplayLanguage language) =>
            (int)language >= 0 && (int)language < LanguageNames.Length ? language : DisplayLanguage.Japanese;
        public static string L(string source) => L(source, UiLanguage);
        public static string L(string source, DisplayLanguage language)
        {
            int index = (int)Normalize(language);
            return index != 0 && Translations.TryGetValue(source, out var values) ? values[index - 1] : source;
        }
        private static readonly Dictionary<string, string[]> Translations = new Dictionary<string, string[]>
        {
            { "左手の指輪", new[] { "Left finger ring", "왼손 손가락 고리", "左手指环", "左手指環" } },
            { "右手の指輪", new[] { "Right finger ring", "오른손 손가락 고리", "右手指环", "右手指環" } },
            { "既存のポーズ操作で親指と人差し指の輪を閉じ、中心と前方（+Z）を合わせて校正を記録してください。輪ソケットはAuto対象外です。ジェスチャーは変更しません。", new[] { "Close the thumb–index ring with your existing pose controls. Align its center and forward (+Z), then capture calibration. Ring sockets are excluded from Auto. Gestures are preserved.", "기존 포즈 도구로 엄지와 검지가 만드는 고리를 닫고 중심과 전방(+Z)을 맞춘 뒤 보정을 기록하세요. 고리 소켓은 Auto 대상에서 제외됩니다. 제스처는 유지됩니다.", "用现有姿势工具让拇指和食指闭合成环，调整中心和前方（+Z），然后记录校准。指环插槽不参与Auto。手势保持不变。", "用現有姿勢工具讓拇指和食指閉合成環，調整中心和前方（+Z），然後記錄校正。指環插槽不參與Auto。手勢保持不變。" } },
            { "親指の重み", new[] { "Thumb weight", "엄지 가중치", "拇指权重", "拇指權重" } },
            { "中心（アバターローカル）", new[] { "Center (avatar local)", "중심(아바타 로컬)", "中心（形象局部坐标）", "中心（化身局部座標）" } },
            { "回転（アバターローカル）", new[] { "Rotation (avatar local)", "회전(아바타 로컬)", "旋转（形象局部坐标）", "旋轉（化身局部座標）" } },
            { "選択Transformを中心に使う", new[] { "Use selected Transform as center", "선택한 Transform을 중심으로 사용", "用所选Transform设置中心", "用所選Transform設定中心" } },
            { "このアバター内のTransformを選択してください。", new[] { "Select a Transform under this avatar.", "이 아바타 아래의 Transform을 선택하세요.", "请选择此形象下的Transform。", "請選擇此化身下的Transform。" } },
            { "校正ハンドルを隠す", new[] { "Hide calibration handle", "보정 핸들 숨기기", "隐藏校准手柄", "隱藏校正控制柄" } },
            { "Sceneで中心を調整", new[] { "Edit center in Scene view", "Scene 뷰에서 중심 조정", "在Scene视图中调整中心", "在Scene視圖中調整中心" } },
            { "輪を閉じた姿勢の校正を記録", new[] { "Capture closed-pose calibration", "고리를 닫은 포즈의 보정 기록", "记录闭环姿势的校准", "記錄閉環姿勢的校正" } },
            { "校正を記録しました。変更を反映すると設定に保存されます。", new[] { "Calibration captured. Apply to save it to the setup.", "보정을 기록했습니다. 변경을 적용하면 설정에 저장됩니다.", "已记录校准。应用更改后保存到设置。", "已記錄校正。套用變更後儲存至設定。" } },
            { "校正記録済み", new[] { "Calibration captured", "보정 기록됨", "已记录校准", "已記錄校正" } },
            { "生成前に校正が必要です", new[] { "Calibration required before generation", "생성 전에 보정이 필요합니다", "生成前需要校准", "產生前需要校正" } },
            { "輪ソケットにはHumanoidアバターが必要です。", new[] { "Finger ring requires a Humanoid avatar.", "고리 소켓에는 Humanoid 아바타가 필요합니다.", "指环插槽需要Humanoid形象。", "指環插槽需要Humanoid化身。" } },
            { "輪ソケットにはThumbDistalとIndexIntermediateが必要です。アバターの関節マッピングを確認してください。", new[] { "Finger ring requires ThumbDistal and IndexIntermediate. Check the avatar's joint mapping.", "고리 소켓에는 ThumbDistal과 IndexIntermediate가 필요합니다. 아바타의 관절 매핑을 확인하세요.", "指环插槽需要ThumbDistal和IndexIntermediate。请检查形象的关节映射。", "指環插槽需要ThumbDistal和IndexIntermediate。請檢查化身的關節對應。" } },
            { "校正の関節はこのアバター内に配置してください。", new[] { "Calibration joints must belong to this avatar.", "보정 관절은 이 아바타 안에 있어야 합니다.", "校准关节必须位于此形象内。", "校正關節必須位於此化身內。" } },
            { "校正には有限値と0～1の重みが必要です。", new[] { "Calibration requires finite values and a weight from 0 to 1.", "보정에는 유한한 값과 0~1 사이의 가중치가 필요합니다.", "校准需要有限数值和0到1之间的权重。", "校正需要有限數值和0到1之間的權重。" } },
            { "輪を閉じて中心と前方を合わせ、生成前に校正を記録してください。", new[] { "Close the finger ring, set its center and forward direction, then capture calibration before generating.", "고리를 닫고 중심과 전방을 맞춘 뒤 생성 전에 보정을 기록하세요.", "闭合指环并设置中心和前方，然后在生成前记录校准。", "閉合指環並設定中心和前方，然後在產生前記錄校正。" } },
            { "指の関節パスが変わりました。校正を記録し直してください。", new[] { "Finger joint paths changed. Capture calibration again.", "손가락 관절 경로가 변경되었습니다. 보정을 다시 기록하세요.", "手指关节路径已改变。请重新记录校准。", "手指關節路徑已改變。請重新記錄校正。" } },
            { "保存された指の校正値が無効です。", new[] { "Invalid saved finger calibration.", "저장된 손가락 보정 값이 유효하지 않습니다.", "保存的手指校准值无效。", "儲存的手指校正值無效。" } },
            { "指の座標系が未設定または無効です。", new[] { "Missing or invalid finger frame.", "손가락 좌표계가 없거나 유효하지 않습니다.", "手指坐标系缺失或无效。", "手指座標系缺失或無效。" } },
            { "現在の輪校正は関節のワールドscaleが1のアバターのみ対応します。", new[] { "Finger calibration currently requires unit world scale on its joint frames.", "현재 고리 보정은 관절의 월드 scale이 1인 아바타만 지원합니다.", "当前指环校准仅支持关节世界scale为1的形象。", "目前指環校正僅支援關節世界scale為1的化身。" } },
            { "輪ソケットにはAuto対象外を明示できるVRCFuryが必要です。", new[] { "Finger ring requires explicit native Auto exclusion support.", "고리 소켓에는 Auto 제외를 명시할 수 있는 VRCFury가 필요합니다.", "指环插槽需要支持明确排除Auto的VRCFury。", "指環插槽需要支援明確排除Auto的VRCFury。" } },
            { "指の輪の校正", new[] { "Finger ring calibration", "손가락 고리 보정", "手指环校准", "手指環校正" } },
            { "カジュアル", new[] { "Casual", "캐주얼", "休闲", "休閒" } },
            { "デフォルト", new[] { "Default", "기본", "默认", "預設" } },
            { "フル", new[] { "Full", "전체", "完整", "完整" } },
            { "メートル", new[] { "Meters", "미터", "米", "公尺" } },
            { "プラグ長", new[] { "Plug length", "플러그 길이", "插入端长度", "插入端長度" } },
            { "ローカル", new[] { "Local", "로컬", "局部", "局部" } },
            { "オブジェクト ON・OFF", new[] { "Object ON/OFF", "오브젝트 ON/OFF", "对象开关", "物件開關" } },
            { "アバター", new[] { "Avatar", "아바타", "虚拟形象", "虛擬化身" } },
            { "プリセット", new[] { "Presets", "프리셋", "预设", "預設" } },
            { "＋ カスタム部位を追加", new[] { "＋ Add custom part", "＋ 커스텀 부위 추가", "＋ 添加自定义部位", "＋ 新增自訂部位" } },
            { "カスタム ", new[] { "Custom ", "커스텀 ", "自定义 ", "自訂 " } },
            { "貫通", new[] { "Through path", "관통", "贯通", "貫通" } },
            { "首付近で太さを0にする", new[] { "Collapse near the neck", "목 근처에서 굵기를 0으로", "在颈部附近将粗细设为0", "在頸部附近將粗細設為0" } },
            { "後方互換性", new[] { "Legacy compatibility", "이전 버전 호환", "旧版兼容", "舊版相容" } },
            { "Modular Avatarで追従", new[] { "Attach with Modular Avatar", "Modular Avatar로 추종", "使用 Modular Avatar 跟随", "使用 Modular Avatar 跟隨" } },
            { "対象アバターを選択してください。以前の対象が開かれている場合は再検出できます。", new[] { "Select an avatar. You can rediscover the previous avatar if it is open.", "대상 아바타를 선택하세요. 이전 아바타가 열려 있으면 다시 찾을 수 있습니다.", "请选择虚拟形象。如果之前的对象已打开，可以重新检测。", "請選擇虛擬化身。如果先前的對象已開啟，可以重新偵測。" } },
            { "対象アバターを再検出", new[] { "Rediscover avatar", "아바타 다시 찾기", "重新检测虚拟形象", "重新偵測虛擬化身" } },
            { "再生を停止すると生成・再生成できます。", new[] { "Stop Play Mode to generate or regenerate.", "재생 모드를 종료하면 생성하거나 다시 생성할 수 있습니다.", "停止播放模式后可生成或重新生成。", "停止播放模式後可產生或重新產生。" } },
            { "プレハブを生成", new[] { "Generate prefab", "프리팹 생성", "生成预制件", "產生 Prefab" } },
            { "プレハブを再生成", new[] { "Regenerate prefab", "프리팹 다시 생성", "重新生成预制件", "重新產生 Prefab" } },
            { "置き換えずに変更を反映", new[] { "Apply without replacing", "교체 없이 변경 적용", "应用更改（不替换）", "套用變更（不取代）" } },
            { "貫通テストプラグ出現", new[] { "Show through-path test plug", "관통 테스트 플러그 표시", "显示贯通测试插入端", "顯示貫通測試插入端" } },
            { "テストプラグ出現", new[] { "Show test plug", "테스트 플러그 표시", "显示测试插入端", "顯示測試插入端" } },
            { "使用", new[] { "Use", "사용", "使用", "使用" } },
            { "深度アクション", new[] { "Depth actions", "깊이 액션", "深度动作", "深度動作" } },
            { "追従先", new[] { "Attach to", "추종 대상", "跟随目标", "跟隨目標" } },
            { "近", new[] { "Near", "가까움", "近", "近" } },
            { "遠", new[] { "Far", "멀리", "远", "遠" } },
            { "メッシュ", new[] { "Mesh", "메시", "网格", "網格" } },
            { "未設定", new[] { "Not set", "미설정", "未设置", "未設定" } },
            { "シェイプ", new[] { "Shape", "셰이프", "形态", "形態" } },
            { "値", new[] { "Value", "값", "值", "值" } },
            { "VRCFury 導入・更新の案内", new[] { "VRCFury install/update guide", "VRCFury 설치·업데이트 안내", "VRCFury 安装及更新指南", "VRCFury 安裝及更新指南" } },
            { "互換性を再確認", new[] { "Recheck compatibility", "호환성 다시 확인", "重新检查兼容性", "重新檢查相容性" } },
            { "この版では利用できません。", new[] { "Unavailable in this version. ", "이 버전에서는 사용할 수 없습니다. ", "此版本不支持。", "此版本不支援。" } },
            { "SPS2 設定", new[] { "SPS2 settings", "SPS2 설정", "SPS2 设置", "SPS2 設定" } },
            { "設定", new[] { "Settings", "설정", "设置", "設定" } },
            { "標準設定・既存Socket", new[] { "Native settings / existing sockets", "기본 설정 / 기존 소켓", "原生设置／现有插槽", "原生設定／現有插槽" } },
            { " 続き", new[] { " continued", " 계속", " 续页", " 續頁" } },
            { "次へ", new[] { "Next", "다음", "下一页", "下一頁" } },
            { "Auto Mode", new[] { "Auto Mode", "자동 모드", "自动模式", "自動模式" } },
            { "Local Only", new[] { "Local Only", "로컬 전용", "仅本地", "僅本機" } },
            { "顔", new[] { "Face", "얼굴", "脸部", "臉部" } },
            { "上半身", new[] { "Upper body", "상체", "上半身", "上半身" } },
            { "手", new[] { "Hands", "손", "手部", "手部" } },
            { "下半身", new[] { "Lower body", "하체", "下半身", "下半身" } },
            { "足", new[] { "Feet", "발", "脚部", "腳部" } },
            { "カスタム", new[] { "Custom", "커스텀", "自定义", "自訂" } },
            { "口", new[] { "Mouth", "입", "嘴", "嘴" } },
            { "左耳", new[] { "Left ear", "왼쪽 귀", "左耳", "左耳" } },
            { "右耳", new[] { "Right ear", "오른쪽 귀", "右耳", "右耳" } },
            { "左乳首", new[] { "Left nipple", "왼쪽 유두", "左乳头", "左乳頭" } },
            { "右乳首", new[] { "Right nipple", "오른쪽 유두", "右乳头", "右乳頭" } },
            { "胸", new[] { "Chest", "가슴", "胸部", "胸部" } },
            { "左手", new[] { "Left hand", "왼손", "左手", "左手" } },
            { "右手", new[] { "Right hand", "오른손", "右手", "右手" } },
            { "両手", new[] { "Both hands", "양손", "双手", "雙手" } },
            { "膣", new[] { "Vagina", "질", "阴道", "陰道" } },
            { "肛門", new[] { "Anus", "항문", "肛门", "肛門" } },
            { "ふとももの間", new[] { "Between thighs", "허벅지 사이", "大腿之间", "大腿之間" } },
            { "左足", new[] { "Left foot", "왼발", "左脚", "左腳" } },
            { "右足", new[] { "Right foot", "오른발", "右脚", "右腳" } },
            { "両足", new[] { "Both feet", "양발", "双脚", "雙腳" } },
            { "画面の言語", new[] { "UI language", "화면 언어", "界面语言", "介面語言" } },
            { "メニューの言語", new[] { "Menu language", "메뉴 언어", "菜单语言", "選單語言" } },
            { "メニュー表示名", new[] { "Menu name", "메뉴 표시 이름", "菜单显示名称", "選單顯示名稱" } },
            { "空欄で標準名を使用します。個別名は言語変更後も保持されます。", new[] { "Leave blank for the standard name. Custom names survive language changes.", "비워 두면 기본 이름을 사용합니다. 개별 이름은 언어를 바꿔도 유지됩니다.", "留空以使用标准名称。自定义名称在切换语言后仍会保留。", "留空以使用標準名稱。自訂名稱在切換語言後仍會保留。" } },
            { "表示名プレビュー", new[] { "Name preview", "이름 미리 보기", "名称预览", "名稱預覽" } },
            { "標準名に戻す", new[] { "Reset name", "기본 이름으로", "恢复标准名称", "還原標準名稱" } },
            { "口-肛門の間にプラグが通る経路を生成します。非常に長いプラグの場合、体を貫通します。\n「首付近で太さを0にする」をオンにすると、口の入口では太さを保ち、首付近から体内の太さを0にします。出口の外では元の太さに戻します。", new[] { "Creates a path from mouth to anus for long plugs.\nCollapse near the neck keeps the entry thickness, reduces internal thickness to zero near the neck, and restores it outside the exit.", "입에서 항문까지 긴 플러그가 통과하는 경로를 만듭니다.\n목 근처에서 굵기를 0으로 설정하면 입구의 굵기는 유지하고 목 근처부터 체내 굵기를 0으로 줄이며 출구 밖에서 복원합니다.", "为长插入端生成从嘴到肛门的路径。\n启用颈部收缩后，入口保持原有粗细，从颈部附近开始体内粗细为0，出口外恢复原有粗细。", "為長插入端產生從嘴到肛門的路徑。\n啟用頸部收縮後，入口保持原有粗細，從頸部附近開始體內粗細為0，出口外恢復原有粗細。" } },
            { "プラグに最も近い対象ソケットを自動で有効にするメニューを追加します。", new[] { "Adds a menu that automatically enables the eligible socket nearest the plug.", "플러그에 가장 가까운 대상 소켓을 자동으로 활성화하는 메뉴를 추가합니다.", "添加自动启用距离插入端最近的目标插槽的菜单。", "新增自動啟用距離插入端最近的目標插槽的選單。" } },
            { "SPS1・DPS・TPSのプラグにも対応させ、互換機能の切り替えメニューを追加します。\nSPS2同士だけで使う場合はオフにできます。", new[] { "Supports SPS1, DPS and TPS plugs and adds a compatibility toggle.\nYou can disable this when only using SPS2.", "SPS1·DPS·TPS 플러그를 지원하고 호환 기능 전환 메뉴를 추가합니다.\nSPS2끼리만 사용하면 꺼도 됩니다.", "支持 SPS1、DPS、TPS 插入端并添加兼容功能开关。\n仅使用 SPS2 时可以关闭。", "支援 SPS1、DPS、TPS 插入端並新增相容功能開關。\n僅使用 SPS2 時可以關閉。" } },
            { "SPS2 の所有ルートが不正です。", new[] { "Invalid SPS2 owned root.", "SPS2 소유 루트가 잘못되었습니다.", "SPS2 所属根对象无效。", "SPS2 所屬根物件無效。" } },
            { "Auto Mode の対象が16個を超えています。", new[] { "Auto Mode has more than 16 sockets.", "자동 모드 대상이 16개를 초과합니다.", "自动模式目标超过16个。", "自動模式目標超過16個。" } },
            { "SPS2 Socket の所有参照が不正です。", new[] { "Invalid SPS2 socket ownership reference.", "SPS2 소켓 소유 참조가 잘못되었습니다.", "SPS2 插槽所属引用无效。", "SPS2 插槽所屬參照無效。" } },
            { "SPS2 ビルドを中止しました: ", new[] { "SPS2 build stopped: ", "SPS2 빌드 중단: ", "SPS2 构建已停止：", "SPS2 建置已停止：" } },
            { "SPS メニューの対応が不明です: ", new[] { "Cannot identify the SPS menu control: ", "SPS 메뉴 항목을 식별할 수 없습니다: ", "无法识别 SPS 菜单控件：", "無法識別 SPS 選單控制項：" } },
            { "VRCFury のビルド結果がありません。", new[] { "VRCFury build output is missing.", "VRCFury 빌드 결과가 없습니다.", "缺少 VRCFury 构建结果。", "缺少 VRCFury 建置結果。" } },
            { "FX Controller の形式が一致しません。", new[] { "Unexpected FX Controller format.", "FX Controller 형식이 일치하지 않습니다.", "FX Controller 格式不匹配。", "FX Controller 格式不符。" } },
            { "SPS2 のビルド前処理がありません。", new[] { "SPS2 build preprocessing is missing.", "SPS2 빌드 전처리가 없습니다.", "缺少 SPS2 构建预处理。", "缺少 SPS2 建置前置處理。" } },
            { "後方互換性メニューがありません。", new[] { "Legacy compatibility menu is missing.", "이전 버전 호환 메뉴가 없습니다.", "缺少旧版兼容菜单。", "缺少舊版相容選單。" } },
            { "SPS パラメーターの対応が不明です。", new[] { "Cannot identify the SPS parameter.", "SPS 파라미터를 식별할 수 없습니다.", "无法识别 SPS 参数。", "無法識別 SPS 參數。" } },
            { "VRCFury API の生成結果がありません: ", new[] { "VRCFury API returned no result: ", "VRCFury API 생성 결과가 없습니다: ", "VRCFury API 未返回生成结果：", "VRCFury API 未傳回產生結果：" } },
            { "VRCFury API がありません: ", new[] { "VRCFury API is unavailable: ", "VRCFury API가 없습니다: ", "VRCFury API 不可用：", "VRCFury API 無法使用：" } },
            { "。VCC で VRCFury を更新してください。", new[] { ". Update VRCFury in VCC.", ". VCC에서 VRCFury를 업데이트하세요.", "。请在 VCC 中更新 VRCFury。", "。請在 VCC 中更新 VRCFury。" } },
            { "SPS Socket がありません。VCC で VRCFury を導入・更新してください。", new[] { "SPS Socket is unavailable. Install or update VRCFury in VCC.", "SPS Socket이 없습니다. VCC에서 VRCFury를 설치하거나 업데이트하세요.", "SPS Socket 不可用。请在 VCC 中安装或更新 VRCFury。", "SPS Socket 無法使用。請在 VCC 中安裝或更新 VRCFury。" } },
            { "この版に Socket モードがありません: ", new[] { "This version lacks Socket mode: ", "이 버전에는 해당 Socket 모드가 없습니다: ", "此版本缺少 Socket 模式：", "此版本缺少 Socket 模式：" } },
            { "追従先の Humanoid ボーンがありません。", new[] { "The target Humanoid bone is missing.", "추종 대상 Humanoid 본이 없습니다.", "缺少目标 Humanoid 骨骼。", "缺少目標 Humanoid 骨骼。" } },
            { "VCC の Manage Project で VRCFury を最新の安定版に更新してください。未導入の場合は VRCFury の公式導入案内をご確認ください。", new[] { "Update VRCFury to the latest stable version in VCC Manage Project. If it is not installed, see the official VRCFury installation guide.", "VCC의 Manage Project에서 VRCFury를 최신 안정 버전으로 업데이트하세요. 설치하지 않았다면 VRCFury 공식 설치 안내를 확인하세요.", "请在 VCC 的 Manage Project 中将 VRCFury 更新到最新稳定版。尚未安装时请参阅 VRCFury 官方安装指南。", "請在 VCC 的 Manage Project 中將 VRCFury 更新到最新穩定版。尚未安裝時請參閱 VRCFury 官方安裝指南。" } },
            { "未導入 / 不明", new[] { "Not installed / unknown", "미설치 / 알 수 없음", "未安装／未知", "未安裝／未知" } },
            { "SPS が見つかりません。プレハブは生成できません。", new[] { "SPS was not found. Cannot generate a prefab.", "SPS를 찾을 수 없습니다. 프리팹을 생성할 수 없습니다.", "未找到 SPS，无法生成预制件。", "找不到 SPS，無法產生 Prefab。" } },
            { "この VRCFury には SPS が搭載されていません。プレハブは生成できません。", new[] { "This VRCFury version has no SPS. Cannot generate a prefab.", "이 VRCFury 버전에는 SPS가 없습니다. 프리팹을 생성할 수 없습니다.", "此 VRCFury 版本不含 SPS，无法生成预制件。", "此 VRCFury 版本不含 SPS，無法產生 Prefab。" } },
            { "SPS の基本設定構造に対応できません。既存設定を守るため生成を停止します。", new[] { "Unsupported SPS settings schema. Generation stopped to preserve existing settings.", "SPS 기본 설정 구조를 지원하지 않습니다. 기존 설정을 보호하기 위해 생성을 중단합니다.", "不支持此 SPS 设置结构。为保留现有设置，已停止生成。", "不支援此 SPS 設定結構。為保留現有設定，已停止產生。" } },
            { "VRCFury の互換性を確認できません: ", new[] { "Cannot check VRCFury compatibility: ", "VRCFury 호환성을 확인할 수 없습니다: ", "无法检查 VRCFury 兼容性：", "無法檢查 VRCFury 相容性：" } },
            { "SPS無印（SPS1）を検出しました。対応する基本ソケットは生成できますが、SPS2 への更新を推奨します。", new[] { "Detected SPS1. Supported basic sockets can be generated; updating to SPS2 is recommended.", "SPS1을 감지했습니다. 지원되는 기본 소켓을 생성할 수 있지만 SPS2 업데이트를 권장합니다.", "检测到 SPS1。可以生成受支持的基础插槽，建议更新至 SPS2。", "偵測到 SPS1。可以產生受支援的基本插槽，建議更新至 SPS2。" } },
            { " はこの版では利用できません（生成対象外）。", new[] { " is unavailable in this version (omitted from generation).", " 기능은 이 버전에서 사용할 수 없어 생성에서 제외됩니다.", "在此版本中不可用（不生成）。", "在此版本中無法使用（不產生）。" } },
            { "貫通経路の曲線調整（標準の経路補間を使用）", new[] { "Through-path curve adjustment (uses default interpolation)", "관통 경로 곡선 조정 (기본 보간 사용)", "贯通路径曲线调整（使用默认插值）", "貫通路徑曲線調整（使用預設插值）" } },
            { "後方互換性の切り替え", new[] { "Legacy compatibility toggle", "이전 버전 호환 전환", "旧版兼容开关", "舊版相容開關" } },
            { "深度アクションの自動設定", new[] { "Automatic depth action setup", "깊이 액션 자동 설정", "自动设置深度动作", "自動設定深度動作" } },
            { "テストプラグ", new[] { "Test plug", "테스트 플러그", "测试插入端", "測試插入端" } },
            { "Radius Offset 非対応のため、標準のソケット配置を使用します。", new[] { "Radius Offset is unsupported; using standard socket placement.", "Radius Offset을 지원하지 않아 기본 소켓 배치를 사용합니다.", "不支持 Radius Offset，将使用标准插槽位置。", "不支援 Radius Offset，將使用標準插槽位置。" } },
            { "追従の公開 API がないため Unity の Parent Constraint を使用します。", new[] { "No public attachment API; using Unity Parent Constraint.", "추종 공개 API가 없어 Unity Parent Constraint를 사용합니다.", "缺少公开跟随 API，将使用 Unity Parent Constraint。", "缺少公開跟隨 API，將使用 Unity Parent Constraint。" } },
            { "VRCFury の設定構造が一致しません: ", new[] { "Unexpected VRCFury settings schema: ", "VRCFury 설정 구조가 일치하지 않습니다: ", "VRCFury 设置结构不匹配：", "VRCFury 設定結構不符：" } },
            { "所有 Socket の参照が失われています。", new[] { "An owned socket reference is missing.", "소유 소켓 참조가 손실되었습니다.", "所属插槽引用丢失。", "所屬插槽參照遺失。" } },
            { "SPS2 セットアップ", new[] { "SPS2 setup", "SPS2 셋업", "SPS2 配置", "SPS2 設置" } },
            { ": 手動で追加された深度グループがあります。設定を保持するため、変更を中止しました。", new[] { ": Manually added depth groups found. Changes stopped to preserve settings.", ": 수동 추가된 깊이 그룹이 있습니다. 설정을 유지하기 위해 변경을 중단했습니다.", "：发现手动添加的深度组。为保留设置，已停止更改。", "：發現手動新增的深度群組。為保留設定，已停止變更。" } },
            { ": BlendShape が未設定のため、このアクションを省きました。", new[] { ": BlendShape is not set; this action was omitted.", ": BlendShape가 설정되지 않아 이 액션을 제외했습니다.", "：未设置 BlendShape，已忽略此动作。", "：未設定 BlendShape，已略過此動作。" } },
            { ": Clip が未設定です。", new[] { ": Clip is not set.", ": Clip이 설정되지 않았습니다.", "：未设置 Clip。", "：未設定 Clip。" } },
            { ": オブジェクトが未設定です。", new[] { ": Object is not set.", ": 오브젝트가 설정되지 않았습니다.", "：未设置对象。", "：未設定物件。" } },
            { "SPS2 設定反映", new[] { "Apply SPS2 settings", "SPS2 설정 적용", "应用 SPS2 设置", "套用 SPS2 設定" } },
            { "SPS2 貫通モード", new[] { "SPS2 through mode", "SPS2 관통 모드", "SPS2 贯通模式", "SPS2 貫通模式" } },
            { "SPS2 共通設定", new[] { "SPS2 shared settings", "SPS2 공통 설정", "SPS2 共用设置", "SPS2 共用設定" } },
            { "Guided Path は最大3通過点です。", new[] { "Guided Path supports at most three waypoints.", "Guided Path는 경유점을 최대 3개 지원합니다.", "Guided Path 最多支持3个途经点。", "Guided Path 最多支援3個途經點。" } },
            { "Guided Path の参照が不正です。", new[] { "Invalid Guided Path reference.", "Guided Path 참조가 잘못되었습니다.", "Guided Path 引用无效。", "Guided Path 參照無效。" } },
            { "この版では貫通経路を利用できません。", new[] { "Through paths are unavailable in this version.", "이 버전에서는 관통 경로를 사용할 수 없습니다.", "此版本不支持贯通路径。", "此版本不支援貫通路徑。" } },
            { "SPS2 貫通設定", new[] { "SPS2 through-path settings", "SPS2 관통 설정", "SPS2 贯通设置", "SPS2 貫通設定" } },
            { "SPS2 体内の太さ", new[] { "SPS2 internal thickness", "SPS2 체내 굵기", "SPS2 体内粗细", "SPS2 體內粗細" } },
            { "貫通経路の区間がありません。", new[] { "Through-path segments are missing.", "관통 경로 구간이 없습니다.", "缺少贯通路径区段。", "缺少貫通路徑區段。" } },
            { "SPS2 貫通経路の接線", new[] { "SPS2 through-path tangents", "SPS2 관통 경로 접선", "SPS2 贯通路径切线", "SPS2 貫通路徑切線" } },
            { "経路の参照またはスケールが不正です。", new[] { "Invalid path references or scale.", "경로 참조 또는 스케일이 잘못되었습니다.", "路径引用或缩放无效。", "路徑參照或縮放無效。" } },
            { "SPS2 設定識別子", new[] { "SPS2 settings identity", "SPS2 설정 식별자", "SPS2 设置标识", "SPS2 設定識別碼" } },
            { "SPS2 の部位識別子が重複しています。", new[] { "Duplicate SPS2 part IDs.", "SPS2 부위 식별자가 중복됩니다.", "SPS2 部位标识重复。", "SPS2 部位識別碼重複。" } },
            { "SPS2 のビルド識別子と既存 Socket が衝突しています。", new[] { "SPS2 build tokens conflict with an existing socket.", "SPS2 빌드 식별자가 기존 소켓과 충돌합니다.", "SPS2 构建标识与现有插槽冲突。", "SPS2 建置識別碼與現有插槽衝突。" } },
            { "SPS2 のビルド識別子と Plug 名が衝突しています。", new[] { "SPS2 build tokens conflict with a plug name.", "SPS2 빌드 식별자가 플러그 이름과 충돌합니다.", "SPS2 构建标识与插入端名称冲突。", "SPS2 建置識別碼與插入端名稱衝突。" } },
            { "SPS2 テストプラグ", new[] { "SPS2 test plug", "SPS2 테스트 플러그", "SPS2 测试插入端", "SPS2 測試插入端" } },
            { "この版ではテストプラグを生成できません。", new[] { "This version cannot generate test plugs.", "이 버전에서는 테스트 플러그를 생성할 수 없습니다.", "此版本无法生成测试插入端。", "此版本無法產生測試插入端。" } },
            { "対応する VRCFury Plug が見つかりません。", new[] { "No matching VRCFury Plug was found.", "일치하는 VRCFury Plug를 찾을 수 없습니다.", "未找到匹配的 VRCFury Plug。", "找不到相符的 VRCFury Plug。" } },
            { "SPS2 生成データの形式が一致しません。", new[] { "Unexpected SPS2 generated data format.", "SPS2 생성 데이터 형식이 일치하지 않습니다.", "SPS2 生成数据格式不匹配。", "SPS2 產生資料格式不符。" } },
            { "SPS2 生成データが欠けています。", new[] { "SPS2 generated data is incomplete.", "SPS2 생성 데이터가 누락되었습니다.", "SPS2 生成数据不完整。", "SPS2 產生資料不完整。" } },
            { "テストプラグが所有ルートの外へ移動されています。", new[] { "The test plug was moved outside its owned root.", "테스트 플러그가 소유 루트 밖으로 이동되었습니다.", "测试插入端已移至所属根对象之外。", "測試插入端已移至所屬根物件之外。" } },
            { "Socket の所有参照が不正です。変更は行いません。", new[] { "Invalid socket ownership reference. No changes made.", "소켓 소유 참조가 잘못되었습니다. 변경하지 않습니다.", "插槽所属引用无效，不作更改。", "插槽所屬參照無效，不作變更。" } },
            { "貫通経路が所有ルートの外を参照しています。", new[] { "The through path references objects outside its owned root.", "관통 경로가 소유 루트 밖을 참조합니다.", "贯通路径引用了所属根对象之外的对象。", "貫通路徑參照了所屬根物件之外的物件。" } },
            { "Scene または Prefab Mode のアバターを選択してください。", new[] { "Select an avatar in a Scene or Prefab Mode.", "Scene 또는 Prefab Mode의 아바타를 선택하세요.", "请选择场景或 Prefab Mode 中的虚拟形象。", "請選擇場景或 Prefab Mode 中的虛擬化身。" } },
            { "部位の識別子が重複または欠落しています。", new[] { "Part IDs are missing or duplicated.", "부위 식별자가 중복되거나 누락되었습니다.", "部位标识缺失或重复。", "部位識別碼缺少或重複。" } },
            { "体の表面を特定できませんでした。ボーンを基準に配置したため、位置と向きを確認してください。", new[] { "Could not locate the body surface. Placement used bones; check positions and rotations.", "신체 표면을 찾지 못했습니다. 본을 기준으로 배치했으므로 위치와 방향을 확인하세요.", "无法定位身体表面。已按骨骼放置，请检查位置和朝向。", "無法定位身體表面。已按骨骼放置，請檢查位置和朝向。" } },
            { "カスタム追従先に自分の生成物は指定できません。", new[] { "A generated object cannot be its own custom attachment target.", "자신의 생성물을 커스텀 추종 대상으로 지정할 수 없습니다.", "不能将自身生成的对象设为自定义跟随目标。", "不能將自身產生的物件設為自訂跟隨目標。" } },
            { ": 追従先が見つからないため省きました。", new[] { ": Attachment target not found; omitted.", ": 추종 대상을 찾을 수 없어 제외했습니다.", "：未找到跟随目标，已忽略。", "：找不到跟隨目標，已略過。" } },
            { "生成できる部位がありません。", new[] { "No parts can be generated.", "생성할 수 있는 부위가 없습니다.", "没有可生成的部位。", "沒有可產生的部位。" } },
            { "追従方式の変更には再生成を使用してください。", new[] { "Regenerate to change the attachment method.", "추종 방식을 변경하려면 다시 생성하세요.", "更改跟随方式需要重新生成。", "變更跟隨方式需要重新產生。" } },
            { ": 生成物が欠けています。再生成してください。", new[] { ": Generated objects are missing. Regenerate the setup.", ": 생성물이 누락되었습니다. 다시 생성하세요.", "：缺少生成对象，请重新生成。", "：缺少產生的物件，請重新產生。" } },
            { "既存分を含む Auto Mode 対象が16個を超えます。Auto Mode を外すか対象を減らしてください。", new[] { "Auto Mode exceeds 16 sockets including existing ones. Disable Auto Mode or reduce the targets.", "기존 소켓을 포함한 자동 모드 대상이 16개를 초과합니다. 자동 모드를 끄거나 대상을 줄이세요.", "包括现有插槽在内，自动模式目标超过16个。请关闭自动模式或减少目标。", "包括現有插槽在內，自動模式目標超過16個。請關閉自動模式或減少目標。" } },
            { "貫通: Neck がないため Head を使用しました。喉の通過点を確認してください。", new[] { "Through path: Neck is missing; used Head. Check the throat waypoint.", "관통: Neck이 없어 Head를 사용했습니다. 목 경유점을 확인하세요.", "贯通：缺少 Neck，已使用 Head。请检查喉部途经点。", "貫通：缺少 Neck，已使用 Head。請檢查喉部途經點。" } },
            { "貫通: 胴体の参照が不足しています。", new[] { "Through path: Torso references are missing.", "관통: 몸통 참조가 부족합니다.", "贯通：缺少躯干引用。", "貫通：缺少軀幹參照。" } },
            { "貫通: 出口の位置を求められませんでした。", new[] { "Through path: Could not locate the exit.", "관통: 출구 위치를 구하지 못했습니다.", "贯通：无法确定出口位置。", "貫通：無法確定出口位置。" } },
            { "先にセットアップを生成してください。", new[] { "Generate the setup first.", "먼저 셋업을 생성하세요.", "请先生成配置。", "請先產生設置。" } },
            { "プラグの表示用アセットが見つかりません。", new[] { "Plug display assets were not found.", "플러그 표시용 에셋을 찾을 수 없습니다.", "未找到插入端显示资源。", "找不到插入端顯示資源。" } },
            { "IcePop の表示用アセットが見つかりません。", new[] { "IcePop display assets were not found.", "IcePop 표시용 에셋을 찾을 수 없습니다.", "未找到 IcePop 显示资源。", "找不到 IcePop 顯示資源。" } },
            { "SPS2 貫通テストプラグ", new[] { "SPS2 through-path test plug", "SPS2 관통 테스트 플러그", "SPS2 贯通测试插入端", "SPS2 貫通測試插入端" } },
            { "IcePop の表示用マテリアルが見つかりません。", new[] { "IcePop display material was not found.", "IcePop 표시용 머티리얼을 찾을 수 없습니다.", "未找到 IcePop 显示材质。", "找不到 IcePop 顯示材質。" } },
            { "貫通テストには口のソケットを生成してください。", new[] { "Generate the mouth socket for through-path testing.", "관통 테스트를 위해 입 소켓을 생성하세요.", "贯通测试需要生成嘴部插槽。", "貫通測試需要產生嘴部插槽。" } },
            { "SPS2 の設定アセットが見つからないか形式が一致しません。Prefab と対応する設定 .asset を一緒に配置してください。", new[] { "SPS2 settings asset is missing or incompatible. Place the prefab together with its matching settings .asset.", "SPS2 설정 에셋이 없거나 형식이 일치하지 않습니다. 프리팹과 해당 설정 .asset을 함께 배치하세요.", "SPS2 设置资源缺失或格式不匹配。请将预制件与对应的设置 .asset 一起放置。", "SPS2 設定資源缺少或格式不符。請將 Prefab 與對應的設定 .asset 一起放置。" } },
            { "設定の参照が対象アバターの外にあります。", new[] { "A settings reference is outside the target avatar.", "설정 참조가 대상 아바타 밖에 있습니다.", "设置引用位于目标虚拟形象之外。", "設定參照位於目標虛擬化身之外。" } },
            { "設定参照の階層名が重複しているか、/ を含んでいます: ", new[] { "A referenced hierarchy name is duplicated or contains /: ", "설정 참조의 계층 이름이 중복되거나 /를 포함합니다: ", "引用的层级名称重复或包含 /：", "參照的階層名稱重複或包含 /：" } },
            { "Animation Clip は保存済みアセットを指定してください。", new[] { "Use a saved Animation Clip asset.", "저장된 Animation Clip 에셋을 지정하세요.", "请使用已保存的 Animation Clip 资源。", "請使用已儲存的 Animation Clip 資源。" } },
            { "SPS2 という名前の生成物がありますが、所有情報を確認できません。", new[] { "An object named SPS2 exists, but its ownership cannot be verified.", "SPS2라는 이름의 생성물이 있지만 소유 정보를 확인할 수 없습니다.", "存在名为 SPS2 的对象，但无法确认其所属信息。", "存在名為 SPS2 的物件，但無法確認其所屬資訊。" } },
            { "対象アバターに複数の SPS2 設定があります。", new[] { "The avatar has multiple SPS2 settings.", "대상 아바타에 SPS2 설정이 여러 개 있습니다.", "目标虚拟形象有多个 SPS2 设置。", "目標虛擬化身有多個 SPS2 設定。" } },
            { "SPS2 生成ルートが見つかりません。", new[] { "SPS2 generated root was not found.", "SPS2 생성 루트를 찾을 수 없습니다.", "未找到 SPS2 生成根对象。", "找不到 SPS2 產生的根物件。" } },
            { "SPS2 Socket の識別子が重複しています。", new[] { "Duplicate SPS2 socket IDs.", "SPS2 소켓 식별자가 중복됩니다.", "SPS2 插槽标识重复。", "SPS2 插槽識別碼重複。" } },
            { "設定アセットに記録されていない SPS2 Socket があります。", new[] { "An SPS2 socket is not recorded in the settings asset.", "설정 에셋에 기록되지 않은 SPS2 소켓이 있습니다.", "存在未记录在设置资源中的 SPS2 插槽。", "存在未記錄在設定資源中的 SPS2 插槽。" } },
            { "VRCFury の列挙型構造が一致しません。", new[] { "VRCFury enum schema mismatch.", "VRCFury 열거형 구조가 일치하지 않습니다.", "VRCFury 枚举结构不匹配。", "VRCFury 列舉結構不符。" } },
            { "VRCFury の列挙値がありません: ", new[] { "VRCFury enum value missing: ", "VRCFury 열거값이 없습니다: ", "缺少 VRCFury 枚举值：", "缺少 VRCFury 列舉值：" } },
            { "不明な深度アクションです。", new[] { "Unknown depth action.", "알 수 없는 깊이 액션입니다.", "未知的深度动作。", "未知的深度動作。" } },
            { "不明なソケット識別子: ", new[] { "Unknown socket identifier: ", "알 수 없는 소켓 식별자: ", "未知的插槽标识：", "未知的插槽識別碼：" } },
            { "VRCAvatarDescriptor を選択してください。", new[] { "Select a VRCAvatarDescriptor.", "VRCAvatarDescriptor를 선택하세요.", "请选择 VRCAvatarDescriptor。", "請選擇 VRCAvatarDescriptor。" } },
            { "選択した Descriptor と同じ GameObject に Animator がありません。", new[] { "The selected descriptor does not have an Animator on the same GameObject.", "선택한 Descriptor와 같은 GameObject에 Animator가 없습니다.", "所选 Descriptor 所在的 GameObject 上没有 Animator。", "所選 Descriptor 所在的 GameObject 上沒有 Animator。" } },
            { "有効な Humanoid Avatar を使用する Descriptor を選択してください。", new[] { "The selected descriptor must use a valid Humanoid Avatar.", "유효한 Humanoid Avatar를 사용하는 Descriptor를 선택하세요.", "所选 Descriptor 必须使用有效的 Humanoid Avatar。", "所選 Descriptor 必須使用有效的 Humanoid Avatar。" } },
            { "追従方式 {0} は利用できません。", new[] { "The {0} attachment backend is unavailable.", "{0} 추종 방식을 사용할 수 없습니다.", "跟随方式 {0} 不可用。", "跟隨方式 {0} 無法使用。" } },
            { "追従方式 {0} が失敗しました: {1}", new[] { "The {0} attachment backend failed: {1}", "{0} 추종 방식이 실패했습니다: {1}", "跟随方式 {0} 失败：{1}", "跟隨方式 {0} 失敗：{1}" } },
        };
    }
}
