var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>(true)).Single(a=>a.name=="MANUKA_lilToon");var clone=UnityEngine.Object.Instantiate(original.gameObject);clone.name="OralAdoptionProbe";
try{var avatar=clone.GetComponent<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>();var root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(avatar);var result=new List<string>{"oldSnapshotLayout="+root.oralBoundaryPath};
 var before=new Dictionary<string,UnityEngine.Vector3[]>();foreach(var id in new[]{"mouth","anus"}){var socket=root.sockets.Single(s=>s.id==id);var a=new UnityEditor.SerializedObject(socket.socket).FindProperty("guidedPathStops");before[id]=Enumerable.Range(0,3).Select(i=>((UnityEngine.Transform)a.GetArrayElementAtIndex(i).FindPropertyRelative("transform").objectReferenceValue).position).ToArray();}
 var settings=root.settings.Copy();string error;if(!LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(avatar,settings,true,out root,out error))throw new System.Exception(error);
 float delta=0;foreach(var id in new[]{"mouth","anus"}){var socket=root.sockets.Single(s=>s.id==id);for(int i=0;i<3;i++)delta=UnityEngine.Mathf.Max(delta,UnityEngine.Vector3.Distance(socket.pathStops[i].position,before[id][i]));}result.Add("acceptedTrialWaypointDelta="+delta);if(delta>1e-5f)throw new System.Exception("Accepted placement mismatch");
 bool[] Flags(string id){var socket=root.sockets.Single(s=>s.id==id);var a=new UnityEditor.SerializedObject(socket.socket).FindProperty("guidedPathStops");return Enumerable.Range(0,a.arraySize).Select(i=>a.GetArrayElementAtIndex(i).FindPropertyRelative("shrink").boolValue).ToArray();}
 void AssertMasks(bool enabled){if(!Flags("mouth").SequenceEqual(new[]{false,enabled,enabled})||!Flags("anus").SequenceEqual(new[]{enabled,enabled,false}))throw new System.Exception("Unexpected mask");}
 root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(avatar);if(!root.oralBoundaryPath)throw new System.Exception("Layout not persisted");AssertMasks(true);
 var mouth=root.sockets.Single(s=>s.id=="mouth");var point=mouth.pathStops[0];point.localPosition+=UnityEngine.Vector3.right*.001f;var pos=point.localPosition;var d=new UnityEditor.SerializedObject(mouth.socket);var tangent=d.FindProperty("guidedPathStops").GetArrayElementAtIndex(0).FindPropertyRelative("tangentOut");tangent.vector3Value+=UnityEngine.Vector3.up*.001f;var tang=tangent.vector3Value;d.ApplyModifiedProperties();
 foreach(bool off in new[]{true,false}){settings.showInternalThickness=off;if(!LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(avatar,settings,false,out root,out error))throw new System.Exception(error);AssertMasks(!off);if(root.sockets.Single(s=>s.id=="mouth").pathStops[0]!=point||point.localPosition!=pos)throw new System.Exception("Manual pose lost");var sd=new UnityEditor.SerializedObject(root.sockets.Single(s=>s.id=="mouth").socket);if(sd.FindProperty("guidedPathStops").GetArrayElementAtIndex(0).FindPropertyRelative("tangentOut").vector3Value!=tang)throw new System.Exception("Manual tangent lost");}result.Add("persistAndTogglePoseTangents=PASS");
 settings.penetration=false;if(!LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(avatar,settings,false,out root,out error))throw new System.Exception(error);if(root.oralBoundaryPath||root.sockets.Any(s=>s.pathStops.Length!=0))throw new System.Exception("Path clear failed");result.Add("clearResetsLayout=PASS");return result;
}finally{UnityEditor.Undo.FlushUndoRecordObjects();foreach(var t in clone.GetComponentsInChildren<UnityEngine.Transform>(true)){foreach(var c in t.GetComponents<UnityEngine.Component>())if(c!=null)UnityEditor.Undo.ClearUndo(c);UnityEditor.Undo.ClearUndo(t.gameObject);}UnityEngine.Object.DestroyImmediate(clone);}
