var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var original=scene.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>(true)).Single(a=>a.name=="MANUKA_lilToon");var avatar=UnityEngine.Object.Instantiate(original.gameObject);avatar.name="OralBoundaryBuild(Clone)";var errors=new List<string>();UnityEngine.Application.LogCallback capture=(m,s,t)=>{if(t==UnityEngine.LogType.Error||t==UnityEngine.LogType.Exception||t==UnityEngine.LogType.Assert)errors.Add(m);};UnityEngine.Application.logMessageReceived+=capture;
try{var descriptor=avatar.GetComponent<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>();var root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(descriptor);if(root==null)throw new System.Exception("Clone ownership missing");var setup=root.settings.Copy();string generationError;if(!LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,setup,true,out root,out generationError))throw new System.Exception(generationError);var mouth=root.sockets.Single(s=>s.id=="mouth");var anus=root.sockets.Single(s=>s.id=="anus");
 bool[] Flags(UnityEngine.Component c){var a=new UnityEditor.SerializedObject(c).FindProperty("guidedPathStops");return Enumerable.Range(0,a.arraySize).Select(i=>a.GetArrayElementAtIndex(i).FindPropertyRelative("shrink").boolValue).ToArray();}
 if(!Flags(mouth.socket).SequenceEqual(new[]{false,true,true})||!Flags(anus.socket).SequenceEqual(new[]{true,true,false}))throw new System.Exception("Collapse masks differ");
 UnityEngine.Vector3[] Points(UnityEngine.Component socket,int i){var s=new UnityEditor.SerializedObject(socket);var a=s.FindProperty("guidedPathStops");var previous=i==0?socket.transform:(UnityEngine.Transform)a.GetArrayElementAtIndex(i-1).FindPropertyRelative("transform").objectReferenceValue;var item=a.GetArrayElementAtIndex(i);var target=(UnityEngine.Transform)item.FindPropertyRelative("transform").objectReferenceValue;return new[]{previous.position,previous.position+previous.rotation*item.FindPropertyRelative("tangentOut").vector3Value,target.position+target.rotation*item.FindPropertyRelative("tangentIn").vector3Value,target.position};}
 float reverseError=0;foreach(int i in new[]{0,1}){var m=Points(mouth.socket,i);var a=Points(anus.socket,2-i);for(int p=0;p<4;p++)reverseError=UnityEngine.Mathf.Max(reverseError,UnityEngine.Vector3.Distance(m[p],a[3-p]));}if(reverseError>1e-5f)throw new System.Exception("Reverse curve mismatch");
 var result=new List<string>{"stops=3/3","collapse=mouth 0/1/1; anus 1/1/0","oralReverseControlError="+reverseError};
 foreach(var c in avatar.GetComponentsInChildren<UnityEngine.MonoBehaviour>(true))if(c!=null&&c!=descriptor&&!c.transform.IsChildOf(root.transform))UnityEngine.Object.DestroyImmediate(c);
 descriptor.customExpressions=false;descriptor.expressionsMenu=null;descriptor.expressionParameters=null;descriptor.customizeAnimationLayers=true;
 foreach(var layers in new[]{descriptor.baseAnimationLayers,descriptor.specialAnimationLayers})for(int i=0;i<layers.Length;i++){var controller=new UnityEditor.Animations.AnimatorController{name="Trial fixture "+layers[i].type};controller.AddLayer("Fixture");var state=controller.layers[0].stateMachine.AddState("Idle");state.writeDefaultValues=true;state.motion=new UnityEngine.AnimationClip();layers[i].isDefault=false;layers[i].animatorController=controller;}
 avatar.GetComponent<UnityEngine.Animator>().runtimeAnimatorController=null;
 bool built=VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks.OnPreprocessAvatar(avatar);result.Add("preprocess="+built);if(!built)throw new System.Exception("Preprocess failed: "+string.Join("|",errors));
 var fx=descriptor.baseAnimationLayers.Single(l=>l.type==VRC.SDK3.Avatars.Components.VRCAvatarDescriptor.AnimLayerType.FX).animatorController;var holes=new Dictionary<string,HashSet<float>>();foreach(var clip in fx.animationClips.Distinct())foreach(var b in UnityEditor.AnimationUtility.GetCurveBindings(clip))if(b.propertyName=="material._SPS_SocketHole"&&(b.path.Contains("mouth")||b.path.Contains("anus"))){if(!holes.ContainsKey(b.path))holes[b.path]=new HashSet<float>();foreach(var k in UnityEditor.AnimationUtility.GetEditorCurve(clip,b).keys)holes[b.path].Add(k.value);}result.Add("nativeMarkers="+string.Join("|",holes.Select(h=>h.Key+"="+string.Join(",",h.Value))));result.Add("missingConstraintSources="+avatar.GetComponentsInChildren<UnityEngine.Animations.ParentConstraint>(true).Count(c=>Enumerable.Range(0,c.sourceCount).Any(i=>c.GetSource(i).sourceTransform==null)));result.Add("actualErrors="+string.Join("|",errors));return result;
}finally{UnityEngine.Application.logMessageReceived-=capture;UnityEngine.Object.DestroyImmediate(avatar);UnityEditor.Selection.activeGameObject=original.gameObject;}
