var original=UnityEngine.SceneManagement.SceneManager.GetActiveScene().GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>(true)).Single(a=>a.name=="MANUKA_lilToon");var avatar=UnityEngine.Object.Instantiate(original.gameObject);avatar.name="Issue121 collapse option probe";
try{
var descriptor=avatar.GetComponent<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>();var settings=LumaKroma.Sps2SetupAssistant.Editor.Model.FullSetupCatalog.CreateDefault();LumaKroma.Sps2SetupAssistant.Editor.Generation.Sps2SetupContext root;string error;var result=new System.Collections.Generic.List<string>();
result.Add("newDefaultOn="+!settings.showInternalThickness+";oldJsonDefaultOn="+!UnityEngine.JsonUtility.FromJson<LumaKroma.Sps2SetupAssistant.SetupSettings>("{\"penetration\":true}").showInternalThickness);
if(!LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,true,out root,out error))return error;
var mouth=root.sockets.Single(s=>s.id=="mouth");var anus=root.sockets.Single(s=>s.id=="anus");var m=new UnityEditor.SerializedObject(mouth.socket);var a=new UnityEditor.SerializedObject(anus.socket);
UnityEngine.Vector3 Control(UnityEditor.SerializedObject data,int index,string field,UnityEngine.Transform frame)=>frame.position+frame.rotation*data.FindProperty("guidedPathStops").GetArrayElementAtIndex(index).FindPropertyRelative(field).vector3Value;
var p0=mouth.pose.position;var p1=Control(m,0,"tangentOut",mouth.pose);var p2=Control(m,0,"tangentIn",mouth.pathStops[0]);var p3=mouth.pathStops[0].position;
result.Add("mouthCurve="+string.Join("|",new[]{p0,p1,p2,p3}.Select(p=>p.ToString("F5"))));result.Add("reverseControlErrors="+UnityEngine.Vector3.Distance(p1,Control(a,2,"tangentIn",anus.pathStops[2]))+","+UnityEngine.Vector3.Distance(p2,Control(a,2,"tangentOut",anus.pathStops[1])));
var point=mouth.pathStops[0];point.localPosition+=UnityEngine.Vector3.right*.001f;var adjusted=point.localPosition;var tangent=m.FindProperty("guidedPathStops").GetArrayElementAtIndex(0).FindPropertyRelative("tangentOut");tangent.vector3Value+=UnityEngine.Vector3.up*.001f;m.ApplyModifiedProperties();var adjustedTangent=tangent.vector3Value;
foreach(bool off in new[]{true,false,true}){settings.showInternalThickness=off;if(!LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,false,out root,out error))return error;root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(descriptor);mouth=root.sockets.Single(s=>s.id=="mouth");m=new UnityEditor.SerializedObject(mouth.socket);result.Add("collapse="+!off+";flags="+string.Join(",",Enumerable.Range(0,3).Select(i=>m.FindProperty("guidedPathStops").GetArrayElementAtIndex(i).FindPropertyRelative("shrink").boolValue))+";saved="+(root.settings.showInternalThickness==off)+";manualPreserved="+(mouth.pathStops[0]==point&&point.localPosition==adjusted&&m.FindProperty("guidedPathStops").GetArrayElementAtIndex(0).FindPropertyRelative("tangentOut").vector3Value==adjustedTangent));}
UnityEditor.Selection.activeGameObject=original.gameObject;UnityEditor.Undo.FlushUndoRecordObjects();UnityEditor.Undo.PerformUndo();root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(descriptor);result.Add("undoCollapseOn="+!root.settings.showInternalThickness);UnityEditor.Undo.PerformRedo();root=LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Find(descriptor);result.Add("redoCollapseOff="+root.settings.showInternalThickness);
settings.penetration=false;LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,false,out root,out error);result.Add("parentOffRetainsPreference="+root.settings.showInternalThickness);settings.penetration=true;LumaKroma.Sps2SetupAssistant.Editor.Generation.FullSetupGenerator.Apply(descriptor,settings,false,out root,out error);result.Add("parentOnCollapseStillOff="+!new UnityEditor.SerializedObject(root.sockets.Single(s=>s.id=="mouth").socket).FindProperty("guidedPathStops").GetArrayElementAtIndex(0).FindPropertyRelative("shrink").boolValue);
return result;
}finally{UnityEditor.Selection.activeGameObject=original.gameObject;UnityEngine.Object.DestroyImmediate(avatar);}
